travis:
  secure:
    BINSTAR_TOKEN: BSF5RzgXQ9Bv7heTKVnakPhJiXDL30oIEoD3bS3MLRToeFW+3fYYAaSLZqk8Dbb/T9M256DxFbYRkWC6I9LL5e7vUQFrD+qfxKXop+/bUZn2fhvIf+zR+b56w3avBJ/20LoVvBIG6/TLvl0QeLdFKdF3pQiL/ggzWyErqqUyl7f/mAeZZd+qigTaGpyjTrrxox85KeEi/h50CNIb7uioqy/DUMeVnwzdcq+zap0E3GGpqZ0roDRGqbTdRsym0tf/rTub2QcqejrmjRIAiNjbthMOLpzFRwHOiWB1EGgQ5fNorFSqr8N0J/5d6AliKr95ny7jjBwjDCccLwM6e0jwm6UzQhpq+D9/bMvY29R/pe3D0n0zIcRYD/rSaHiV+w2bQ+ijQQR/75+imm5ZEwQCYGQQjql5+4XcENIS09TuVy9fQlXFGgIT79GcB3HM9o+4qU6CsCgvne5uHSZYtEpswowFxbJSCdv2jwu8c9F0CRaJz37pJb6t0a7UZtJClyg6qWC2UqQLGIXDBKhOZccJupGc8PDazf8FiKNe4DbmTlRm06WbXy5luqUAvc7Kmzs1saH4cRaTzwyRs5Oken1ko49zO/VrPBP3sRNKv22T9cgACVWhlngO2Y9yShHANoOv/aQh6aIzqX2AjbeK5gKkoIxWprP5CCIPnfiMpEU1FZs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
