travis:
  secure:
    BINSTAR_TOKEN: orbOfQQOD/P3SNwObuVSzCScpIW55j6X7mB+B2N4H3NlP0LNXTnVWQrsQzFXSqJ31tXvWyY8mFkKgtPY8IuMiOBmgpsD7J2RRlgpO9Ee3dntbqsX5b4m0DW5LbvUOBwEro5f1R6H7PengcGj/uNkMoRlTrgBp4+0I1xYokwfzCtRUkqjcD/vi/O0EOTzG6PHaTWp90z1MHBW37frlGOxan7hhbrwcW8Bg/mlTczg4hfRLamEYZpIRzrAK9Mj5+JPgDL6NETpDPWeFt84OMqAuTwQ6BWoXlgnzkp7gJkxav12o/QNFaZYi2a53kH1WswRk32tdtxX2xZhM2MvKQOGenlqHUpBlFuKsZoAz/T33dVtesLHQh4zle+Oq/Rr0zU+UpJjqMQip2hetw89CryvzzbV/c0ckFQBXXRX8bZPC+lhwAJMPDwrQLeG5AX5yeIgjEIFosclX8orshYDwBDNZL46Q3ayl5Nk6wMo7ht11cX6WUcjCu79xJZ4m0EpMq3ZPeXpnHhEb3kclMg0vm9zaEkSW64teO2rdN00X5cvKubS7PfKYJeul++fuTnRzctvl9iWFhAAMIW0CzLuuyQjip8jhRkJWJpZSLslCuVdt7HRMcibY3Hfsbcji1QgBTUSjt4QkuXG8jOabTqQW4KWpNp7P6gJantgAL5z6X0IcIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
